### PR TITLE
Upgrade to .NET Core 3, remove Json.NET depedency, minor refactors

### PR DESCRIPTION
**Pull request by developervariety**

### CODE REVIEW

**Comment by OhSoooLucky** [comment]
+1

**Comment by OhSoooLucky** [comment]
Perhaps this project should be targetting netstandard2.x rather than netcoreapp3.0

**Comment by DejanPelzel** [comment]
Thank you for the pull request, really appreciated. However, there we have some concerns.  We're trying to stick with the lowest .NET core version to keep compatibility with older projects, so not sure how good idea it would be to lock into .NET Core 3 and use the System.Text.Json despite the slightly better performance? As such I'm a bit hesitant on merging this.

A small thing, internally we're used to using this keyword for accessing properties within the class. Not sure if this clashes with the general code styling?

**Comment by OhSoooLucky** [comment]
I will create a new PR containing compatibility for netstandard 2.0 and netstandard 2.1.
Would that suffice for backwards compatibility?

**Pull request closed without merging**
